# Tensor Operationen

## Tensoroperationen sind stark optimiert

In [5]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]): 
            x[i, j] = max(x[i, j], 0)
    return x

In [6]:
def naive_add(x, y):
    assert len(x.shape) == 2 
    assert x.shape == y.shape 
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]): 
            x[i, j] += y[i, j]
    return x

In [7]:
import numpy as np 

x = np.random.random((20, 100)) 
y = np.random.random((20, 100)) 



In [8]:
%timeit z = x + y

1.3 µs ± 49.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [9]:
%timeit z = naive_add(x, y)

692 µs ± 38.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
z = x + y
%timeit zz = np.maximum(z, 0.)

3.79 µs ± 120 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
%timeit zz = naive_relu(z)

1.03 ms ± 11.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Broadcasting Beispiel

In [16]:
# Die Grundrechenarten und die Anwendung von Funktionen sind elementwise definiert
x = np.random.random((64, 3, 32, 10)) 
y = np.random.random((32, 10))
z = np.maximum(x, y)

In [17]:
z.shape

(64, 3, 32, 10)

In [18]:
y

array([[[[0.23040801, 0.74197584, 0.22604452, ..., 0.57613664,
          0.63934209, 0.15714841],
         [0.99909803, 0.61152527, 0.38569805, ..., 0.31262246,
          0.61544011, 0.16926998],
         [0.91320834, 0.99120814, 0.8651067 , ..., 0.19373665,
          0.19020087, 0.95932511],
         ...,
         [0.17735142, 0.17439246, 0.83941649, ..., 0.61450814,
          0.86050011, 0.31746739],
         [0.85764539, 0.32604915, 0.87066634, ..., 0.35218257,
          0.53543676, 0.57250729],
         [0.47252049, 0.19896443, 0.55962205, ..., 0.9585874 ,
          0.70232185, 0.62881542]],

        [[0.91062043, 0.44186983, 0.59572971, ..., 0.65497407,
          0.01719964, 0.37823115],
         [0.17608266, 0.39362847, 0.33478845, ..., 0.3363777 ,
          0.08186139, 0.30138499],
         [0.25840065, 0.30179062, 0.98826192, ..., 0.44002352,
          0.12601395, 0.37744491],
         ...,
         [0.13051661, 0.05801152, 0.47208917, ..., 0.58161891,
          0.09940406, 0.0

# Dot Produkt

In [21]:
x = np.random.random((32)) 
y = np.random.random((32)) 
z = np.dot(x, y)

In [23]:
z.shape

()

In [25]:
x = np.random.random((1,32)) 
y = np.random.random((32,1)) 
z = np.dot(x, y)

In [27]:
z

array([[7.69231973]])

In [28]:
# VORSICHT! MANCHE MENSCHEN MEINEN DOT-PRODUKT SOLLTE AUCH BEI MATRIZEN SKALAREN OUTPUT HABEN
x = np.random.random((32,5)) 
y = np.random.random((5,32)) 
z = np.dot(x, y)

In [29]:
z.shape

(32, 32)

In [32]:
x = np.random.random((9,3,4,8))
y = np.random.random((8,2)) # aber (8,2,3) geht nicht.

z = np.dot(x,y)
z.shape

(9, 3, 4, 2)

In [37]:
x = np.array([1,2,3]) 
x.shape

(3,)

In [41]:
def naive_vector_dot(x, y):
    assert len(x.shape) == 1 
    assert len(y.shape) == 1 
    assert x.shape[0] == y.shape[0] 
    
    z = 0.
    for i in range(x.shape[0]): 
        z += x[i] * y[i]
    return z

In [42]:
def naive_matrix_vector_dot(x, y): 
    assert len(x.shape) == 2 
    assert len(y.shape) == 1 
    assert x.shape[1] == y.shape[0] 
    
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]): 
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]
    return z

# Übung
* Benchmarken der beiden naiven "vector_dot"-Implementierungen vs Numpy
* Wie ändert sich die Runtime mit der Dimensionalität des Inputs?

In [53]:
x = np.random.random((8))
y = np.random.random((8)) # aber (8,2,3) geht nicht.
len(x.shape)
x

array([0.89513447, 0.15025122, 0.77060433, 0.10314203, 0.05014465,
       0.31232442, 0.43535527, 0.21983594])

In [46]:
%timeit z = naive_vector_dot(x, y)

2.97 µs ± 93.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [50]:
%timeit z = np.dot(x,y)

919 ns ± 40.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


(8,)

# Tensor Reshaping

In [56]:
x = np.array([[0., 1.], 
              [2., 3.],
              [4., 5.]])
x.shape

(3, 2)

In [57]:
x = x.reshape((6, 1))

In [58]:
x

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [59]:
x = x.reshape((2,3))
x

array([[0., 1., 2.],
       [3., 4., 5.]])

In [60]:
x = x.reshape((3,2))
x

array([[0., 1.],
       [2., 3.],
       [4., 5.]])

In [61]:
# Aber: transponieren ändert die Reihenfolge
x = x.transpose()
x

array([[0., 2., 4.],
       [1., 3., 5.]])

In [62]:
x = x.reshape((3,2))
x

array([[0., 2.],
       [4., 1.],
       [3., 5.]])